[colors]
transparent_background_colors = true

[colors.primary]
# background = "#f0f0f0"
# background = "#c8c8c8"
# foreground = "#121212" 
background = "#191724"
foreground = "#e0def4" 

[colors.normal]
black = "#121212"
white = "#f0f0f0"
green = "#4e9a06"
blue = "#729fcf"
red = "#cc0000"
