# theme = "catppuccin_macchiato"
theme = "rose_pine"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"
bufferline = "multiple"
cursorline = true
shell = [ "cmd", "/C" ]
color-modes = true
rulers = [ 80 ]
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"

[editor.lsp]
auto-signature-help = false
display-inlay-hints = true

[editor.statusline]
left = [ "mode", "spinner", "file-name", "file-modification-indicator" ] 
center = ["position", "total-line-numbers", "register"]
right = [ "workspace-diagnostics", "diagnostics", "file-encoding", "file-type", "version-control" ]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.indent-guides]
render = true
character = "⸽"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker] 
hidden = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
"'" = "'"
'"' = '"'
'`' = '`'
'<' = '>'


[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 1000

[editor.soft-wrap]
enable = true
max-wrap = 15
max-indent-retain = 30



[keys.normal]
esc = [ "collapse_selection", "keep_primary_selection"]

# Extra Text Movements
C-j = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
C-k = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
ret = "goto_word"


# Quick File State Management
space.q = ":wq" # Save and Quit

# Windows Management
space.v = ":vsplit" # Vertical Split
C-l = [ "jump_view_right" ]
C-h = [ "jump_view_left" ]
C-q = [ "wclose" ]

# Buffers


# Text Manipulation
[keys.normal.Y]
d = [ "extend_to_line_bounds", "yank", "toggle_comments", "paste_after"] # Duplicate line and comment out the first one
p =  ":clipboard-paste-replace"
8 = "switch_case"
l = "switch_to_lowercase"
u = "switch_to_uppercase"

# TOOLS
[keys.normal.T]
g = [ ":new", ":insert-output lazygit", ":buffer-close!", ":redraw" ]# Git Integration through Lazygit
y = [ ':sh del E:\Packages\yazi\yazi-path.txt',
':insert-output yazi --chooser-file=E:\Packages\yazi\yazi-path.txt',
':open %sh{type E:\Packages\yazi\yazi-path.txt}',
":redraw"
] # File Explorer through Yazi - WIP

# Terminal State Management
[keys.normal.backspace]
backspace = "suspend"
c = ":buffer-close"
C = ":buffer-close!"
y = ":yank-diagnostic"



[keys.insert]
# Extra Insert Actions
C-backspace = [ "move_prev_word_start", "delete_selection_noyank" ]
C-left = [ "move_prev_word_start" ] # Move by a whole word to left
C-right = [ "move_next_word_start" ] # Move by a whole word to right
