[language-server.vls]
command = "vls"

[[language]]
name = "go"
language-servers = [ { name = "gopls"} ]

[[language]]
name = "vue"
language-servers = [ { name = "prettier", only-features = [ "format" ]}, "vls" ]
formatter = { command = "prettier" }

[[language]]
name = "html"
# language-servers = [ { name = "", only-features = [ "format" ]}, "vscode-html-languageservice"]
# formatter = { command = "prettier" } 
scope = "source.html"
roots = []
file-types = ["html"]
language-servers = [ "superhtml-lsp" ]

[language-server.superhtml-lsp]
command = "superhtml"
args = ["lsp"]

[language-server.ruff]
command = "ruff"
args = [ "server" ]

[[language]]
name = "python"
language-servers = ["ruff", "pylsp"]
auto-format = false
